Fix GNU build error
Commit aecb9989 ("Fixes perfect restart issue in the ICE_SHELF
module", 2017-04-07) introduced calls to `pass_var()` within a
subroutine whose `ocean_grid_type` structure was `intent(in)`. Most
compilers seem to be happy with this, but certain versions of gfortran
would fail with the following error:

      call pass_var(CS%area_shelf_h, G%domain)
                                     1
    Error: Procedure argument at (1) is INTENT(IN) while interface specifies INTENT(INOUT)

Changing the argument to `intent(inout)` fixes this.